id: P010620
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG6168
  title: བྱང་ཆུབ་ལམ་སྒྲོན་གྱི་འགྲེལ་བ་མར་གྱི་ཉིང་ཁུ།
  author: ''
  volumes:
    c206a7c796084f4b837c6f6ae51c6b19:
      image_group_id: I1KG8463
      title: ''
      volume_number: 1
      total_pages: 382
      base_file: v001.txt
